### PR TITLE
Add nickname Format option

### PR DESCRIPTION
**Pull request by pokertour**
I've added a nickname format option. 
It's working the only problem is that i can't read the value from the config.json file so i set it up directly for the test.

The format are :
FULL : Take the full name input
HALF : Take the firstname and the first letter of the lastname
FIRST : Take only the firstname

### CODE REVIEW

**Comment by pokertour** [comment]
#14

**Comment by DarkArtek** [comment]
always open to contributions. Let me do some tests and see if i can read the config.

in the VA I flew, the full name was usually used. That's why I set up the bot like this.

**Comment by pokertour** [comment]
Yes i've tested it, and it's working, the PR is very simple, you can modify it if you want i'm not a JS dev :D 
The only problem i encounter is that the configuration is not reading my setting in the config.json So when i've tested it, instead of putting : const NICK_FORMAT = configFile.nickFormat; in the configuration.js i've put : const NICK_FORMAT = "HALF";

**Comment by pokertour** [comment]
Thank's for the merge, but as you can see in https://github.com/DarkArtek/vamsys-discord-access-bot/blob/v2/src/constants/configuration.js

There is to line for the nickname format, the current active is a workarround because it seem i can't add setting in config.json, when i do this i got the const undefined.

Do you know why ?

**Pull request merged**
